//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeEcommers.LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public Campaigns()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UrlImageMedium { get; set; }
        public string UrlImagePrincipal { get; set; }
        public int OrderCamp { get; set; }
        public Nullable<int> OrderPrincipal { get; set; }
        public Nullable<bool> IsPrincipal { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
