//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeEcommers.LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public Cards()
        {
            this.Pays = new HashSet<Pays>();
        }
    
        public int Id { get; set; }
        public int IdCustomer { get; set; }
        public string CardEnd { get; set; }
        public string TypeCard { get; set; }
        public System.DateTime ExpiredDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<Pays> Pays { get; set; }
    }
}
