//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeEcommers.LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.SubCategories = new HashSet<SubCategories>();
        }
    
        public int Id { get; set; }
        public int IdDepartment { get; set; }
        public string Category { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<SubCategories> SubCategories { get; set; }
    }
}
