//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeEcommers.LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public int IdCard { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
