//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeEcommers.LogicLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategories
    {
        public SubCategories()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public int IdCategory { get; set; }
        public string SubCategory { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
